name: proyecto_acustica
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - librosa
  - soundfile
  - pyaudio
  - pandas
  - scikit-learn
  - pygame
  - ffmpeg
  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu121
      - torchvision --index-url https://download.pytorch.org/whl/cu121
      - torchaudio --index-url https://download.pytorch.org/whl/cu121
